<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class admission extends Model
{

     protected $fillable = [
    	'surname', 
    	'firstname', 
    	'middlename',
    	'address',
    	'citizenship',
		'telephone',
		'mobile',
		'email',
		'birthdate',
		'birthplace',
		'birth_order',
		'sibling_b',
		'sibling_s',
		'religion',
		'baptism',
		'baptism_place',
		'church',
		'language',
		'schoolattend',
		'sa_address',
		'sa_level',
		'sa_year',
		'f_surname',
		'f_firstname',
		'f_middlename',
		'f_address',
		'f_telephone',
		'f_mobile',
		'f_email',
		'f_occupation',
		'f_bname',
		'f_bemail',
		'f_company_address', 
		'm_maidename',
		'm_firstname',
		'm_middlename',
		'm_telephone',
		'm_mobile',
		'm_email',
		'm_occupation',
		'm_bname',
		'm_bemail',
		'm_company_address',
		'f_grade_school_name',
		'f_grade_school_address',
		'f_grade_school_degree',
		'f_grade_school_school_year_attended',
		'f_hs_school_name',
		'f_hs_school_address',
		'f_hs_school_degree',
		'f_hs_school_school_year_attended',
		'f_college_school_name',
		'f_college_school_address',
		'f_college_school_degree',
		'f_college_school_school_year_attended',
		'f_post_graduate_school_name',
		'f_post_graduate_school_address',
		'f_post_graduate_school_degree',
		'f_post_graduate_school_school_year_attended',
		'm_grade_school_name',
		'm_grade_school_address',
		'm_grade_school_degree',
		'm_grade_school_school_year_attended',
		'm_hs_school_name',
		'm_hs_school_address',
		'm_hs_school_degree',
		'm_hs_school_school_year_attended',
		'm_college_school_name',
		'm_college_school_address',
		'm_college_school_degree',
		'm_college_school_school_year_attended',
		'm_post_graduate_school_name',
		'm_post_graduate_school_address',
		'm_post_graduate_school_degree',
		'm_post_graduate_school_school_year_attended',
		'father_citizenship',
		'mother_citizenship',
		'sibling_name',
		'sibling_birthdate',
		'sibling_age',
		'sibling_sex',
		'sibling_gr',
		'theraphy',
];
}

